FROM python:3.12

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && \
    apt-get install -y netcat-openbsd && \
    rm -rf /var/lib/apt/lists/*

COPY . .

CMD ["sh", "-c", "while ! nc -z postgres_test 5432; do sleep 1; echo 'Waiting for PostgreSQL...'; done && python -m pytest -v"]
