networks:
  test_network:
    driver: bridge

services:
  postgres_test:
    image: postgres:15-alpine
    container_name: test_dbZUS
    networks:
      - test_network
    env_file: .env.test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api_test:
    build: .
    container_name: test_apiZUS
    networks:
      - test_network
    ports:
      - "8001:8000"
    depends_on:
      - postgres_test
    env_file: .env.test

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: testZUS
    networks:
      - test_network
    depends_on:
      - postgres_test
      - api_test
    env_file: .env.test

