from os import getenv

from dotenv import load_dotenv

load_dotenv()

POSTGRES_HOST = getenv("POSTGRES_HOST")
POSTGRES_PORT = getenv("POSTGRES_PORT")
DB_PASSWORD = getenv("POSTGRES_PASSWORD")
POSTGRES_USER = getenv("POSTGRES_USER")
POSTGRES_DB = getenv("POSTGRES_DB")

SQLALCHEMY_DATABASE_URL = f"postgresql+asyncpg://{POSTGRES_USER}:{DB_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"
LOCAL_SQLALCHEMY_DATABASE_URL = f"postgresql+asyncpg://{POSTGRES_USER}:{DB_PASSWORD}@localhost:{POSTGRES_PORT}/{POSTGRES_DB}"

STAND = getenv("STAND")
if STAND == "TEST":
    MIGRATION_SQLALCHEMY_DATABASE_URL = SQLALCHEMY_DATABASE_URL
elif STAND == "DEV":
    MIGRATION_SQLALCHEMY_DATABASE_URL = LOCAL_SQLALCHEMY_DATABASE_URL
else:
    raise ValueError("не задан стенд в env, миграции куда катить?")
