"""solved ненужон

Revision ID: 014225d121d1
Revises: e5415db7dab5
Create Date: 2025-07-11 00:08:28.372375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014225d121d1'
down_revision: Union[str, Sequence[str], None] = 'e5415db7dab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('table', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('variables', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('formula', sa.String(length=255), nullable=True))
    op.drop_column('tasks', 'is_solved')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_solved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'formula')
    op.drop_column('tasks', 'variables')
    op.drop_column('tasks', 'table')
    # ### end Alembic commands ###
