"""есть ли разница для бд в наследнике?

Revision ID: 8b7d66fd1838
Revises: 96663c8133fd
Create Date: 2025-07-17 22:54:07.786482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b7d66fd1838'
down_revision: Union[str, Sequence[str], None] = '96663c8133fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oneactiontasklink', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('taskfilelink', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('taskgraphlink', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tasktheorylink', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('theoryfilelink', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('theorygraphlink', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theorygraphlink', 'created_at')
    op.drop_column('theoryfilelink', 'created_at')
    op.drop_column('tasktheorylink', 'created_at')
    op.drop_column('taskgraphlink', 'created_at')
    op.drop_column('taskfilelink', 'created_at')
    op.drop_column('oneactiontasklink', 'created_at')
    # ### end Alembic commands ###
