"""дано для задач в 1 формулу

Revision ID: cbcd73572a78
Revises: b1ade37c16bc
Create Date: 2025-07-13 00:31:17.630278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbcd73572a78'
down_revision: Union[str, Sequence[str], None] = 'b1ade37c16bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oneactionformula',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula', sa.String(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('param_ranges', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oneactionformula')
    # ### end Alembic commands ###
