"""Hello tasks

Revision ID: e5415db7dab5
Revises: 6c25c4323aaa
Create Date: 2025-07-09 21:11:56.079135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5415db7dab5'
down_revision: Union[str, Sequence[str], None] = '6c25c4323aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_data',
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('x', sa.JSON(), nullable=False),
    sa.Column('y', sa.JSON(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_data_id'), 'graph_data', ['id'], unique=False)
    op.create_table('task_images',
    sa.Column('base64', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_images_id'), 'task_images', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer_options', sa.JSON(), nullable=True),
    sa.Column('correct_answers', sa.JSON(), nullable=False),
    sa.Column('user_answers', sa.JSON(), nullable=True),
    sa.Column('is_solved', sa.Boolean(), nullable=True),
    sa.Column('solved_at', sa.DateTime(), nullable=True),
    sa.Column('graph_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['graph_id'], ['graph_data.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['task_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_task_images_id'), table_name='task_images')
    op.drop_table('task_images')
    op.drop_index(op.f('ix_graph_data_id'), table_name='graph_data')
    op.drop_table('graph_data')
    # ### end Alembic commands ###
